### ISSUE TITLE
♻️ CodeAuditor report - Fix bad HTML code

### ISSUE THREAD

**Issue by tombui99** [SSWConsulting/SSW.People#481]
Cc: @adamcogan @william-liebenberg @bradystroud 

Hi @BrookJeynes 

### Pain

As per our conversation, we need to fix bad HTML code in SSW People from CodeAuditor report and reduce the numbers of code errors and warnings.

See https://codeauditor.com/latest/02ad5e57-04e6-4c4f-bdd4-1e62d495e6d5/ssw.com.au%2Fpeople for latest scan on SSW People

```[tasklist]
### Tasks
<!--Add GitHub tasks-->
- [ ] Check latest scan from CodeAuditor to see code errors and warnings
- [ ] Fix the HTML code in SSW People accordingly
- [ ] Rerun the scan and check if code errors and warnings have gone down
- [ ] Give me an update
```

### Screenshots

![image](https://github.com/SSWConsulting/SSW.People/assets/67776356/3b8c8088-64c8-412c-823a-27e1a7868ce0)

**Figure: Latest scan report from [CodeAuditor](https://codeauditor.com/build/c9942feb-0e24-4861-63aa-66be54a832c1)**

Thanks!

**Comment by BrookJeynes** [comment]
Closing as this has been moved into 3 separate issues:
- https://github.com/SSWConsulting/SSW.People/issues/484
- https://github.com/SSWConsulting/SSW.People/issues/483
- https://github.com/SSWConsulting/SSW.People/issues/482
