### ISSUE TITLE
♻️ Fix CodeAuditor ⚠️ warnings

### ISSUE THREAD

**Issue by BrookJeynes** [SSWConsulting/SSW.People#484]
Version 0

Cc: @bradystroud @Aibono1225 @adamcogan @tombui99 

Hi Team,

This is a long lasting PBI item to ensure every Sprint some time is spent working on reducing the amount of ⚠️ **warnings** CodeAuditor is finding.

The latest scan can be found here: https://codeauditor.com/latest/02ad5e57-04e6-4c4f-bdd4-1e62d495e6d5/ssw.com.au%2Frules

### Tasks

- [ ] Work on reducing the ⚠️ **warnings** every Sprint
- [ ] Increment the version number each Sprint using the "Change x to y" rule (https://www.ssw.com.au/rules/change-from-x-to-y/) (this is to track history)
- [ ] Comment on the PBI every Sprint with the following information:
    - The PRs that were made in relation to fixing CodeAuditor errors (each PR fixing CodeAuditor issues should be marked with the "CodeAuditor" tag)
    - The diff from last Sprint (screenshots)

Thanks!

< As per https://ssw.com.au/rules/managing-errors-with-code-auditor/ >

**Comment by PothieuG** [comment]
Duplicate: https://github.com/SSWConsulting/SSW.Rules/issues/985
