### ISSUE TITLE
Move SkillUrlData.json to CRM

### ISSUE THREAD

**Issue by BrookJeynes** [SSWConsulting/SSW.People#496]
CC: @bradystroud @christianmorfordwaitessw @zl24622 

Hey Team,

Currently skills data comes from two different places:
- CRM: Data for skills on each profile
    ![Screenshot 2023-07-11 at 13 59 55](https://github.com/SSWConsulting/SSW.People/assets/25432120/98736a09-2687-4e0a-ae63-212340bad851)
- SkillURLData.json: Data for skills on sidebar
    ![Screenshot 2023-07-11 at 14 00 32](https://github.com/SSWConsulting/SSW.People/assets/25432120/58931d8d-cd0c-4af1-9eae-4ca38d920c3d)

SkillURLData.json seems to only hold the data for which SSW consulting page to redirect each skill to. There is no reason for this data to be in two separate places. Each skill would therefore have an optional URL field specifying, if required, which consulting page to re-direct to.

![image](https://github.com/SSWConsulting/SSW.People/assets/25432120/a1146821-5832-4b8e-9f8f-8946e2e444d6)
**Figure: SkillURLData.json snippet**

As per my conversation with @zl24622, he will be adding an optional field "Consulting Page URL" to each skill.

Once Lu has added the field then

```[tasklist]
### Tasks
- [x] Transfer the data from SkillURLData.json into CRM
- [x] Update People so that all the data comes from CRM
- [x] Remove the old skills json file
- [ ] Missing Skills - Audit the skills that are now hidden (we are only showing ones with service pages)
- [ ] Missing Skills - Are any of these important?
- [x] Update the SSW People documentation
```

**Comment by zl24622** [comment]
@BrookJeynes 

> As per my conversation with @zl24622, he will be adding an optional field "Consulting Page URL" to each skill.

Done - added the field in the Skill 

<img width="841" alt="image" src="https://github.com/SSWConsulting/SSW.People/assets/8521734/20648b51-a939-46e0-b46c-e63cba2ae4c1">

**Comment by bradystroud** [comment]
Hey @BrookJeynes @zl24622 can you discuss this with @wicksipedia and @pierssinclairssw before proceeding? They are working on similar stuff

**Comment by BrookJeynes** [comment]
CC: @bradystroud @adamcogan @zl24622 

As per my conversation with @pierssinclairssw, him and @wicksipedia have drafted up a solution to this problem and it's different to the one being actioned here but is still in CRM. Piers and Matt see the relationship between skills and consulting pages as many to many.

1. Before implementing, get the solution checked by @pierssinclairssw, @wicksipedia, and @adamcogan

**Comment by pierssinclairssw** [comment]
Hi @zl24622 @bradystroud @adamcogan @BrookJeynes 

Here is what @wicksipedia  and I discussed in regards to this problem (**not approved for implementation**):


Currently, there is a disconnect between skills that are added in CRM/displayed on SSW People and what is actually sold to clients. We believe that the Consulting Services page should be the source of truth for what we sell to clients, and the skills in CRM should link back to the website.

For example, GitHub Actions in the CRM would link back to the consulting page for ALM and Azure DevOps.
 
Additionally, we think there should be better quality control on skills in CRM and this could be achieved by forcing people to enter a link to a consulting page.
 
That way we don’t end up with skills like “Musician” which don’t relate to what SSW sells as a company.
 
This would also solve issues with having a “Magic json” file to define our important skills. That file could be removed and replaced with CRM data.
https://github.com/SSWConsulting/SSW.People/blob/main/SkillUrlData.json
 
And here are the tasks we were planning to assign:

### For the Dynamics Team

1.	Add another table for Consulting Services in CRM
a.	The table should contain a field for a link to a consulting services web page.
2.	Add another table for Consulting Services Skills in CRM
a.	It should have a “priority” field to determine which is the number 1
3.	Make sure these views can be seen for all SSW Employees
Note: Multiple skills could link to a single web page (e.g. GitHub and Azure DevOps would both link to ALM and vice versa, ALM and Scrum may both link to Azure DevOps)
4.	Make the skills require at least 1 Consulting Service
 
### For Website Team
 
1.	Once CRM team tasks are done, fix up SSW People to read from CRM instead of the magic JSON file.
2.	Update the process for Consulting Services pages so that when they are created or updated, CRM is also updated.
e.g. add a reminder on the website CMS edit experience
 
![image](https://github.com/SSWConsulting/SSW.People/assets/79821522/d89fe7da-0bcc-4545-ad7c-8068e20ec2d1)
**Figure: Musician makes little sense to exist on our skills page**

**Comment by adamcogan** [comment]
Awesome solution Wicksy and Piers ⭐
 
Hi @zl24622 
Moving from the .json file to a CRM Dataverse Table (aka Entity) is much better.

1. Please implement their suggested solution in Dynamics (2 new tables as it is many-many relationship) 😊

2. Add PowerBI Report which shows which consulting services an employee can and cannot do.

3. Work with Piers to replace the Annual Review PDF with the Power BI report

-a

**Comment by zl24622** [comment]
cc @adamcogan 

As per conversation with @pierssinclairssw  and  @wicksipedia 

@sethdailyssw  

- [ ] Please update the Github Issue form [https://github.com/SSWConsulting/SSW.Website/issues/new?assignees=&labels=&projects=&template=new_webpage.yml&title=📄+%7B%7B+TITLE+%7D%7D+] to include a link to CRM consulting service record. The field should be required.  (Tell the user to put N/A if it's not a consulting service page)

@bradystroud  

- [ ]  Please work on the People website to read the consulting service data from CRM to replace the JSON file

**Comment by sethdailyssw** [comment]
cc @adamcogan 
@zl24622 @pierssinclairssw @wicksipedia 

> Please update the [Github Issue form](https://github.com/SSWConsulting/SSW.Website/issues/new?assignees=&labels=&projects=&template=new_webpage.yml&title=📄+%7B%7B+TITLE+%7D%7D+) to include a link to CRM consulting service record. The field should be required. (Tell the user to put N/A if it's not a consulting service page)

Done via https://github.com/SSWConsulting/SSW.Website/pull/1437

**Comment by BrookJeynes** [comment]
> Update People so that all the data comes from CRM

Done - Both the data for each user profile and technologies filtering list come from CRM. The technologies filter in the sidebar is now linked with CRM. This means that when a new technology/skill is created in CRM, it will appear in the search bar (assuming it's been approved and has a valid marketing page)

> Remove the old skills json file

Done 🎉 

> Update the SSW People documentation

There is no documentation needing to be updated. The skills for each users still come from CRM therefore the process of adding one to a profile remains the same.
