### ISSUE TITLE
🐛SSW People Audio URL UX is very confusing

### ISSUE THREAD

**Issue by piers-sinclair** [SSWConsulting/SSW.People#520]
On SSW People, I followed the instructions for adding an Audio URL.

It didn't work. I tried changing the format of the audio URL in GitHub...I also tried adding the link via CRM...nothing seemed to work.

Finally I made the audio URL match the file name requested exactly and it worked. This experience is very poor as the user would not expect the file name to have to match someone's name exactly when there is a URL stored in CRM.

```[tasklist]
### Tasks
- [ ] Investigate what the CRM URL is used for
- [ ] Make it so the CRM URL is the source of truth....don't force the file name to match an exact format. 
- [ ] Checked by Brady then Piers
```
