### ISSUE TITLE
🇨🇳 China site - Why so many versions?

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.People#521]
cc @pierssinclairssw @JeanThirion @AlvinShenSSW @hveraus @adamcogan 

⚠️ As per my conversation with @pierssinclairssw.  This should be solved before the French SSW Péople is built, otherwise we are building a lot of tech debt 😬

For SSW People China we have 2 different pages
- https://ssw.com.cn/ourPeople?lang=zh-CN
- https://peoplecn.ssw.com.au/people-cn/ (not working, but works on staging https://staging.ssw.com.au/people-cn/?location=All)

```[tasklist]
### Tasks
- [ ] Organise a meeting (@jerryluossw @pierssinclairssw @wicksipedia @william-liebenberg @GordonBeeming @JeanThirion)    to discuss the following: 
- [ ] Why are there 2 SSW People Chinas?
- [ ] Look at analytics - are they both used?
- [ ] How can we better approach internationalisation for our websites?
- [ ] Hosting - do we need to host them separately to make sure they are accessible to everyone?
```  

This is related to this thread _RE: SSW.France - I want /people integrated_

**Comment by zacharykeeping** [comment]
Hey guys,

Is there an update to this? We're getting a lot of broken links popping up in recent CodeAuditor scans as every page links to [https://peoplecn.ssw.com.au/](https://peoplecn.ssw.com.au/people-cn/) in the language dropdown in the top right: https://codeauditor.com/build/92c26c5a-441d-4db8-5c22-e69c3c726e54
