### ISSUE TITLE
♻️ Install GTM on SSW.People

### ISSUE THREAD

**Issue by Aibono1225** [SSWConsulting/SSW.People#525]
cc @bradystroud @tiagov8 @camillars 

Relates to https://github.com/SSWConsulting/SSW.Rules/issues/1064

To Myself,

We are going to install GTM on SSW People.

```[tasklist]
### Tasks
- [x] Move rules analytics (Analytics) to the Rules GTM Container
- [x] Install GTM on People
- [x] Remove existing analytics from People (these are replaced by GTM)
```

**Comment by Aibono1225** [comment]
⭐Done

![image](https://github.com/SSWConsulting/SSW.People/assets/127192800/b833f0db-37b8-4f3b-9c7b-ebc22fc9381b)
