### ISSUE TITLE
🐛 Weird `/tom` redirect behaviour

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.People#534]
https://www.ssw.com.au/people/tom/ takes me to Tom I's page
https://www.ssw.com.au/people/tom takes me to Tom B's page

```[tasklist]
### Tasks
- [x] Why is this the behavior?
- [x] We cannot use /tom if there are 2 Toms - remove the shortcut for both
- [x] Check this for Wills, Lukes, Jacks any other duplicate names
```

**Comment by tiagov8** [comment]
cc @tombui99

**Comment by Aibono1225** [comment]
**Option 1: Remove the shortcut if there are two identical names. (minor changes to the Rules content)**
✅ `https://www.ssw.com.au/people/tom-iwainski`  to Tom I
✅ `https://www.ssw.com.au/people/tom-bui`  to Tom B
❌ `https://www.ssw.com.au/people/tom` 

**Option 2: Do not use nicknames in the URL anymore. (big changes to the Rules content):**
✅ `https://ssw.com.au/people/kaique-biancatti`
❌ `https://ssw.com.au/people/kiki`

**Option 3: Whether or not there is a slash at the end of the URL, it should navigate to the page of the people who have that nickname**
`https://www.ssw.com.au/people/tom`  to Tom I
`https://www.ssw.com.au/people/tom/`  to Tom I
`https://www.ssw.com.au/people/tom-bui`  to Tom B
`https://www.ssw.com.au/people/tom-bui/`  to Tom B

As per my conversation with @bradystroud , we have decided to go for option 1. 🙂

**Comment by Aibono1225** [comment]
> Why is this the behavior?

We have an incorrect redirect rule in https://ssw.com.au/people/rewritemaps.xml: `<add key="/people/tom" value="/people/tom-bui"/>`

As a result, entering `/people/tom` in the URL take us to Tom B's page, while entering `people/tom/` takes us to Tom I's page due to the default setting.

![image](https://github.com/SSWConsulting/SSW.People/assets/127192800/e7b929f6-eb57-450b-bbfd-b8aa9fa2c1a1)

**Comment by tiagov8** [comment]
FYI - I think Option 2 is the way to go. 

See related Issue: https://github.com/SSWConsulting/SSW.People/issues/541

**Comment by bradystroud** [comment]
@tiagov8 

⚠️ Option 2 will break a lot of existing links, outside of just rule content
Going forward, I dont think we should allow anyone to create nickname links but we should keep the old ones alive

Hey @Aibono1225 

1. Please update any docs/SL items that mention adding nicknames

**Comment by tiagov8** [comment]
Hi @Aibono1225 / @bradystroud

Even if we are not changing the existing nicnames, can we have a list of who are using nicknames? 
Maybe have that list in the Wiki and link to it from the SugarLearning.

I think it's important to:
- Potentially find other similar nicknames
- Possibly remove at least the ones for alumni or people that don't have many rules

**Comment by Aibono1225** [comment]
Hi @tiagov8 ,

Here is a list of URLs that use nicknames:
```
/people/sample/
/people/cammy/
/people/alumni/dave/
/people/dhruv/
/people/alumni/gabe/
/people/jk/
/people/jim/
/people/kiki/
/people/alumni/lachie/
/people/alumni/marni/
/people/mehmet/
/people/alumni/mike/
/people/penny/
/people/alumni/seb/
/people/alumni/taq/
/people/toby/
/people/uly/
/people/alumni/will/
```

This list was generated by filtering the content of https://ssw.com.au/people/rewritemaps.xml 😉

**Comment by tiagov8** [comment]
Hi @Aibono1225 

I want to make this list shorter and easier to maintain

Once you have the [Acknowledgements User Page](https://github.com/SSWConsulting/SSW.Rules/issues/1046) up and running...

- [ ] 1. Please double check every page for employees with nicknames 
- [ ] 2. Remove the nickname/redirect for all employees that are **not** authors of any rules
- [ ] 3. Remove the nickname/redirect for employees that are authors of **5 or less rules**
- [ ] 4. Fix the author links on each of the 'less than 5' rules per employee (add @tiagov8 as the reviewer)
- [ ] 5. Send here an updated list of employees with nicknames
- [ ] 6. Go for option 1 (as per above) for /tom

**Comment by tiagov8** [comment]
PS. I've found a mention in this Wiki about nicknames and changed it to a "Note:" saying it's not recommeded.

https://github.com/SSWConsulting/SSW.People.Profiles/wiki/3.-Updating-CRM#name-widget

**Comment by tiagov8** [comment]
cc @tomek-i

**Comment by JackDevAU** [comment]
Closing and moving the new task to: https://github.com/SSWConsulting/SSW.People/issues/562
