### ISSUE TITLE
♻️REFACTOR - Nicknames are no longer recommended 

### ISSUE THREAD

**Issue by JackDevAU** [SSWConsulting/SSW.People#562]
CC: @tiagov8 @bradystroud @Aibono1225 @tomek-i 

Copied from https://github.com/SSWConsulting/SSW.People/issues/534#issuecomment-1756144453 and turned into a new issue.

Hey Team,

Nicknames are no longer recommended and have caused previous issues with redirects. 

### Tasks

> TIP: You can get the list of pages that have nicknames via [ssw.com.au/people/rewritemaps.xml](https://ssw.com.au/people/rewritemaps.xml) 
> Here is an old list:
```
/people/sample/
/people/cammy/
/people/alumni/dave/
/people/dhruv/
/people/alumni/gabe/
/people/jk/
/people/jim/
/people/kiki/
/people/alumni/lachie/
/people/alumni/marni/
/people/mehmet/
/people/alumni/mike/
/people/penny/
/people/alumni/seb/
/people/alumni/taq/
/people/toby/
/people/uly/
/people/alumni/will/
```

- [ ] 1. Please double check every page for employees with nicknames
- [ ] 2. Remove the nickname/redirect for all employees that are not authors of any rules
- [ ] 3. Remove the nickname/redirect for employees that are authors of 5 or less rules
- [ ] 4. Fix the author links on each of the 'less than 5' rules per employee (add @tiagov8 as the reviewer)
- [ ] 5. Send here an updated list of employees with nicknames
- [x] 6. Go for option 1 (as per above) for /tom (See https://github.com/SSWConsulting/SSW.People/issues/534#issuecomment-1726836690)

**Comment by Aibono1225** [comment]
Updated requirements as per my conversation with @tiagov8 

- [ ] SSW.People - make all SSW.People.Profiles pages to have the full name as the default
- [ ] SSW.SugarLearning -  Update Induction to not mention using nicknames for future profiles
- [ ] SSW.Rules - do a `search and replace` on SSW.Rules.Content to replace all nicknames with full names

**Comment by Aibono1225** [comment]
Hi @tiagov8 ,

> SSW.SugarLearning - Update Induction to not mention using nicknames for future profiles

🤔 It just hit me that the nickname we see in the profile is fetched from CRM. If we don't want any new nickname being used in the future, I think maybe we should disable the nickname field in the CRM (making it not editable):
![image](https://github.com/SSWConsulting/SSW.People/assets/127192800/e5aa60f0-d3c4-4781-84f0-316bd7ee3afa)

If the goal is simply to inform people not to use a nickname in the author link when they create or update rule content, there is already a notification in this [wiki](https://github.com/SSWConsulting/SSW.Rules.Content/wiki/How-to-Add-an-Acknowledgment) stating that using a nickname is not recommended.

**Comment by JackDevAU** [comment]
Hey @Aibono1225 

Not a bad idea! 

If we get approval from @adamcogan and @tiagov8 let's get @zl24622 to make the change in CRM :)

**Comment by tomek-i** [comment]
The problem is  **not** the nickname field in CRM.
The problem is SSW.People prioritises and uses the nickname field to generate a unique slug which is the problem

Since I started and followed the SL items and added my CRM info + nickname it caused conflicts with Tom Bui's account.

What needs to be fixed is SSW.People and how the url's / slugs to the people are generated.

I think it's fine to leave the nickname on CRM and let people know their preferred way of addressing them.

**Comment by JackDevAU** [comment]
> The problem is **not** the nickname field in CRM. I think it's fine to leave the nickname on CRM and let people know their preferred way of addressing them.
> 
> The problem is SSW.People prioritises and uses the nickname field to generate a unique slug which is the problem
> 
> Since I started and followed the SL items and added my CRM info + nickname it caused conflicts with Tom Bui's account since we both added `Tom` as our nicknames.
> 
> What needs to be fixed is SSW.People and how the url's / slugs to the people are generated. Even firstname + lastname combination would eventually be a problem if we get 2 people with the same first/lastname like `John Snow`.

Yea that's another issue.... 
Guess we can't employee people with the same name 😂😂

**Comment by tiagov8** [comment]
+1 to @tomek-i comment.

We don't want to disable the possibility of having a nickname, we just want to avoid it being used on SSW.People and SSW.Rules, since we need to avoid duplicates and even confusion (which one to use? name or nickname?)

**Comment by tomek-i** [comment]
> > SSW.People - make all SSW.People.Profiles pages to have the full name as the default.
> 
> Done ⭐
> 
> SSW.People is now using fullname as the default.
> 
> When users click on a nickname link, they will also be redirected to the correct link. Example: https://ssw.com.au/people/taq will go to https://ssw.com.au/people/alumni/taqwa-hasyim/ https://ssw.com.au/people/uly will go to https://ssw.com.au/people/ulysses-maclaren/
> 
> ![image](https://private-user-images.githubusercontent.com/127192800/303580484-408eef5d-fa46-4da6-83da-b1625ff00ecd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2ODk0OTAsIm5iZiI6MTcwNzY4OTE5MCwicGF0aCI6Ii8xMjcxOTI4MDAvMzAzNTgwNDg0LTQwOGVlZjVkLWZhNDYtNGRhNi04M2RhLWIxNjI1ZmYwMGVjZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMVQyMjA2MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMWRlYWFmYWNiYzlkY2RiZTlmYjJiZjZiYjUwZGY4NWU0M2I1MGU0N2YyNmJmNmJhOGNjYWQ4M2ViNDJiMmJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ImXBdNLGUXs6LYyOSChwd-pCFZOAG-q9pde1tBQCkUg)
> 
> > SSW.SugarLearning - Update Induction to not mention using nicknames for future profiles
> 
> Not done because the [SugarLearning item](https://my.sugarlearning.com/SSW/items/9369/how-to-write-ssw-rules) already has a link to our [Rule's wiki](https://github.com/SSWConsulting/SSW.Rules.Content/wiki/How-to-Add-an-Acknowledgment)
> 
> > SSW.Rules - do a search and replace on SSW.Rules.Content to replace all nicknames with full names
> 
> Done via [SSWConsulting/SSW.Rules.Content#7929](https://github.com/SSWConsulting/SSW.Rules.Content/pull/7929)

What about duplicate names like 2 people with the name "John Smith"? Because that's going to be the next problem eventually.

**Comment by JackDevAU** [comment]
> > > SSW.People - make all SSW.People.Profiles pages to have the full name as the default.
> > 
> > 
> > Done ⭐
> > SSW.People is now using fullname as the default.
> > When users click on a nickname link, they will also be redirected to the correct link. Example: [ssw.com.au/people/taq](https://ssw.com.au/people/taq) will go to [ssw.com.au/people/alumni/taqwa-hasyim](https://ssw.com.au/people/alumni/taqwa-hasyim/) [ssw.com.au/people/uly](https://ssw.com.au/people/uly) will go to [ssw.com.au/people/ulysses-maclaren](https://ssw.com.au/people/ulysses-maclaren/)
> > ![image](https://private-user-images.githubusercontent.com/127192800/303580484-408eef5d-fa46-4da6-83da-b1625ff00ecd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2ODk0OTAsIm5iZiI6MTcwNzY4OTE5MCwicGF0aCI6Ii8xMjcxOTI4MDAvMzAzNTgwNDg0LTQwOGVlZjVkLWZhNDYtNGRhNi04M2RhLWIxNjI1ZmYwMGVjZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMVQyMjA2MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMWRlYWFmYWNiYzlkY2RiZTlmYjJiZjZiYjUwZGY4NWU0M2I1MGU0N2YyNmJmNmJhOGNjYWQ4M2ViNDJiMmJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ImXBdNLGUXs6LYyOSChwd-pCFZOAG-q9pde1tBQCkUg)
> > > SSW.SugarLearning - Update Induction to not mention using nicknames for future profiles
> > 
> > 
> > Not done because the [SugarLearning item](https://my.sugarlearning.com/SSW/items/9369/how-to-write-ssw-rules) already has a link to our [Rule's wiki](https://github.com/SSWConsulting/SSW.Rules.Content/wiki/How-to-Add-an-Acknowledgment)
> > > SSW.Rules - do a search and replace on SSW.Rules.Content to replace all nicknames with full names
> > 
> > 
> > Done via [SSWConsulting/SSW.Rules.Content#7929](https://github.com/SSWConsulting/SSW.Rules.Content/pull/7929)
> 
> What about duplicate names like 2 people with the name "John Smith"? Because that's going to be the next problem eventually.

--

I've created a new issue to tackle this: https://github.com/SSWConsulting/SSW.People/issues/601
