### ISSUE TITLE
⚠️ Deployments - change from VM to Blob storage

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.People#622]
Cc: @adamcogan 

We need to decommission the VM we are deploying to and as a result switch to Azure Storage (blob storage)

```[tasklist]
### Tasks
- [x] Migrate builds/deployments from AzDO Pipelines to GitHub Actions?
- [x] Spin up Azure storage account and enable web server
- [x] Change deployments from IIS WebDeploy to AZ CLI file copy
- [ ] Change Cloudflare config to route `/people` to new storage account
```

### Screenshots

Thanks!

**Comment by wicksipedia** [comment]
update on this issue - `main` now deploys to a new staging environment - https://sapeoplestagjthgmptzb46i.z8.web.core.windows.net/people

`release/*` branches will deploy to a new prod environment - https://sapeopleprod7bktxxg33i3v.z8.web.core.windows.net/people

I'd warn against creating a new prod release as there are some breaking changes:

- redirects are page driver (not IIS driven)
- filters do NOT work on staging - they potentially need a rewrite

**Comment by wicksipedia** [comment]
reopening - due to outstanding tasks

**Comment by jernejk** [comment]
Adding a few tasks for this.

## Filters not working on staging

```[tasklist]
### Tasks
- [ ] Investigate how filters are working
- [ ] Diagnose why filters break in staging but not locally
- [ ] Fix
```

##

**Comment by jernejk** [comment]
I have created a PR to push Profile changes to staging:
https://github.com/SSWConsulting/SSW.People.Profiles/pull/1210

As per my conversation with @wicksipedia, it should be more consistent with SSW.Rules and using GH workflows instead of sh script. I initially tried to write YAML code but deleted it as it was too hard to verify it without permissions to run workflows. I'll ask SysAdmins to gain access.

NOTE: Fixed build issue that prevented CRM changes to get into production. https://github.com/SSWConsulting/SSW.People/issues/650

**Comment by wicksipedia** [comment]
The GitHub Action to trigger the build would look like https://github.com/SSWConsulting/SSW.Rules.Content/blob/main/.github/workflows/main-trigger-rules-deploy.yml

It uses app registration to get a token to do the workflow_dispatch

**Comment by jernejk** [comment]
✅ All done.
