### ISSUE TITLE
⚠️🚀 People Deployments - change from VM to Blob storage

### ISSUE THREAD

**Issue by JackDevAU** [SSWConsulting/SSW.People#637]
CC @adamcogan @bradystroud @wicksipedia @Aibono1225 

Hey Team, 

Now that we have successfully done this for SSW Rules (awesome stuff!!) [✅ Done - Rules change from VM to Blob storage](https://github.com/SSWConsulting/SSW.Rules/issues/1292)
Let's do the same for SSW.People. 

```[tasklist]
### Tasks
- [ ] GitHub Deployment - Spin up Azure storage account and enable web server 
- [ ] Change deployments from IIS WebDeploy to AZ CLI file copy
- [ ] Change GitHub Action on SSW People Content repo to trigger this new action
- [ ] Change Azure Front Door config to route /people to new storage account 
```

**Comment by wicksipedia** [comment]
was closed as dupe of #622
