### ISSUE TITLE
🐛 Unable to load correct config on staging

### ISSUE THREAD

**Issue by jernejk** [SSWConsulting/SSW.People#646]
cc: @wicksipedia, @adamcogan, @bradystroud, @Calinator444 

When we fixed the staging deployment due to Application Insights hard crashing React, we noticed that more configurations are not loaded correctly on staging.

We noticed that the recommended configuration for localhost has a different format than the `.evn.template` used by staging and later production. Current production is still based on the old deployment which is likely why it still works.

```[tasklist]
### Tasks
- [ ] Fix `.env.template`
- [ ] Verify configs are loaded correctly
- [ ] Migrate Application Insights Instrument Key to Connection String as per my conversation with @wicksipedia 
```
