### ISSUE TITLE
💚 Update Application Insights to use Connection String instead of Instrumentation Key

### ISSUE THREAD

**Issue by jernejk** [SSWConsulting/SSW.People#648]
cc: @wicksipedia @adamcogan 

Microsoft changed the recommended way of configuring Application Insights from using Instrumentation Keys to Connection Strings. As per my conversation with @wicksipedia, we should update this.

```[tasklist]
### Tasks
- [ ] Update the code that loads the connection string
- [ ] Update environment variables from `APPINSIGHTS_INSTRUMENTATIONKEY` to `APPINSIGHTS_CONNECTIONSTRING`
- [ ] Update GitHub environment variables
```

**Comment by jernejk** [comment]
Done but needs #651 to be deployable.
