### ISSUE TITLE
🚀 Update build & deploy process to have information on how it was triggered

### ISSUE THREAD

**Issue by jernejk** [SSWConsulting/SSW.People#655]
Hi team,

As per my conversation with @wicksipedia, it would be great to know what triggered "Production - build and deploy" like being triggered by CRM skills update or a person's markdown changed.

```[tasklist]
### Tasks
- [x] Update "Production - build and deploy" workflow to accept trigger source, defaulting "branch-change"
- [x] Update "Rolling Production Build" in SSW.People.Profiles repo to be "CRM-skill"
- [x] Update "Trigger-People-Build" in SSW.People.Profiles repo to be "people-changed"
```

**Comment by jernejk** [comment]
✅ All done :)
